<?php

/**
 * Create a new course in Moodle.
 * @param string $fullname Full course name.
 * @param string $shortname Short course name (must be unique).
 * @return int Course ID.
 * @throws moodle_exception if creation fails.
 */
function local_aicoursegen_create_course($fullname, $shortname) {
    global $CFG, $DB;
    require_once($CFG->dirroot . '/course/lib.php');

    // Find a category (use default category 1, or fallback to the first one).
    $category = $DB->get_record('course_categories', ['id' => 1]);
    if (!$category) {
        $category = $DB->get_record('course_categories', [], IGNORE_MULTIPLE);
    }
    if (!$category) {
        throw new moodle_exception('error', 'local_aicoursegen', '', 'No course category found.');
    }

    // Ensure shortname is unique.
    $shortname = trim($shortname);
    if (empty($shortname)) {
        $shortname = 'AI_' . substr(md5(microtime()), 0, 8);
    }
    // If shortname already exists, append a random suffix.
    if ($DB->record_exists('course', ['shortname' => $shortname])) {
        $shortname .= '_' . substr(md5(microtime()), 0, 4);
    }

    $course = new stdClass();
    $course->fullname  = $fullname;
    $course->shortname = $shortname;
    $course->category  = $category->id;
    $course->summary   = 'Generated by AI Course Generator';
    $course->format    = 'topics';
    $course->numsections = 0; // will be updated later
    $course->visible   = 0;   // hidden until ready

    $created = create_course($course);
    if (!$created || empty($created->id)) {
        throw new moodle_exception('error', 'local_aicoursegen', '', 'Failed to create course.');
    }
    return (int)$created->id;
}

/**
 * Call the FastAPI endpoint to generate course materials.
 *
 * @param string $filepath  Absolute path to the uploaded PDF.
 * @param array  $params    Associative array of request parameters.
 * @return array            Decoded JSON response.
 * @throws moodle_exception on HTTP or cURL error.
 */
function local_aicoursegen_call_fastapi($filepath, $params) {
    $api_base = rtrim(get_config('local_aicoursegen', 'api_base_url'), '/');
    $api_key  = get_config('local_aicoursegen', 'api_key');

    $url = $api_base . '/course/generate';
    $ch  = curl_init($url);

    $postfields = [
        'file'           => new CurlFile($filepath, 'application/pdf', basename($filepath)),
        'title'          => $params['title'],
        'num_lectures'   => $params['num_lectures'],
        'include_quizzes'=> $params['include_quizzes'] ? 'true' : 'false',
        'moodle_export'  => 'true',
    ];
    if (!empty($params['description'])) {
        $postfields['description'] = $params['description'];
    }

    curl_setopt($ch, CURLOPT_POST,          true);
    curl_setopt($ch, CURLOPT_POSTFIELDS,    $postfields);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER,true);
    curl_setopt($ch, CURLOPT_TIMEOUT,       600);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER,false); // development only

    if ($api_key) {
        curl_setopt($ch, CURLOPT_HTTPHEADER, ['X-API-Key: ' . $api_key]);
    }

    $response = curl_exec($ch);
    $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $error    = curl_error($ch);
    curl_close($ch);

    if ($httpcode !== 200) {
        throw new moodle_exception('error', 'local_aicoursegen', '',
            'HTTP ' . $httpcode . ': ' . $response . ' cURL error: ' . $error);
    }

    return json_decode($response, true);
}

/**
 * Download a file from a URL with proper encoding.
 *
 * @param string $url  Remote URL.
 * @return string      Binary file content.
 * @throws moodle_exception on failure.
 */
function local_aicoursegen_download_file($url) {
    // Encode spaces and other problematic characters.
    $url = str_replace(' ', '%20', $url);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL,            $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_TIMEOUT,        120);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_USERAGENT,      'Moodle-AI-CourseGen/1.0');

    $data      = curl_exec($ch);
    $httpcode  = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $error     = curl_error($ch);
    $effective = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
    curl_close($ch);

    if ($data === false || $httpcode !== 200) {
        throw new moodle_exception('error', 'local_aicoursegen', '',
            'Download failed. HTTP code: ' . $httpcode .
            ', URL: '        . $effective .
            ', cURL error: ' . $error);
    }

    return $data;
}

/**
 * Add a file resource (PDF) to a course section.
 *
 * @param int    $courseid    The course ID.
 * @param string $name        Resource name shown in Moodle.
 * @param string $filecontent Binary content of the PDF.
 * @param int    $section     Section number (0-based).
 * @return int                Course-module ID of the newly created resource.
 * @throws moodle_exception   If the course ID is invalid or creation fails.
 */
function local_aicoursegen_add_file_resource($courseid, $name, $filecontent, $section = 0) {
    global $CFG, $DB, $USER;

    // Load all required libs BEFORE any constants are referenced.
    require_once($CFG->dirroot . '/course/lib.php');
    require_once($CFG->dirroot . '/course/modlib.php');
    require_once($CFG->libdir  . '/filelib.php');
    require_once($CFG->dirroot . '/mod/resource/lib.php'); // defines RESOURCELIB_DISPLAY_* constants

    // Safety-net: define constants if the include above somehow didn't expose them
    // (e.g. resource mod not installed). Values match mod/resource/lib.php.
    if (!defined('RESOURCELIB_DISPLAY_AUTO'))  { define('RESOURCELIB_DISPLAY_AUTO',  0); }
    if (!defined('RESOURCELIB_DISPLAY_EMBED')) { define('RESOURCELIB_DISPLAY_EMBED', 1); }
    if (!defined('RESOURCELIB_DISPLAY_OPEN'))  { define('RESOURCELIB_DISPLAY_OPEN',  2); }

    // ── 1. Validate course ────────────────────────────────────────────────────
    $courseid = (int)$courseid;
    if ($courseid <= 0 || !$DB->record_exists('course', ['id' => $courseid])) {
        throw new moodle_exception('error', 'local_aicoursegen', '',
            'Invalid course ID: ' . $courseid);
    }

    $course  = $DB->get_record('course', ['id' => $courseid], '*', MUST_EXIST);
    $context = context_course::instance($courseid);

    // ── 2. Store the PDF in a user draft area ─────────────────────────────────
    $fs      = get_file_storage();
    $draftid = file_get_unused_draft_itemid();

    $userctx = context_user::instance($USER->id);

    $filerecord = [
        'contextid' => $userctx->id,   // must be the USER draft context
        'component' => 'user',
        'filearea'  => 'draft',
        'itemid'    => $draftid,
        'filepath'  => '/',
        'filename'  => clean_filename($name) . '.pdf',
        'userid'    => $USER->id,
    ];

    $fs->create_file_from_string((object)$filerecord, $filecontent);

    // ── 3. Build moduleinfo ───────────────────────────────────────────────────
    // create_module() calls the module's add_moduleinfo() under the hood, which
    // calls editors_preprocess_params() — that function requires 'introeditor'
    // (not a plain 'intro' string).

    $moduleinfo                   = new stdClass();
    $moduleinfo->modulename       = 'resource';
    $moduleinfo->module           = $DB->get_field('modules', 'id', ['name' => 'resource'], MUST_EXIST);
    $moduleinfo->course           = $courseid;
    $moduleinfo->section          = (int)$section;
    $moduleinfo->visible          = 1;
    $moduleinfo->visibleoncoursepage = 1;
    $moduleinfo->name             = $name;

    // introeditor is what create_module / add_moduleinfo actually expects.
    $moduleinfo->introeditor      = [
        'text'   => '',
        'format' => FORMAT_HTML,
        'itemid' => 0,
    ];

    // Display options for the resource module.
    $moduleinfo->display          = RESOURCELIB_DISPLAY_AUTO;   // defined in mod/resource/lib.php
    $moduleinfo->filterfiles      = 0;
    $moduleinfo->showexpanded     = 1;
    $moduleinfo->showsize         = 0;
    $moduleinfo->showtype         = 0;
    $moduleinfo->showdate         = 0;

    // The draft file-manager field — resource mod reads 'files'.
    $moduleinfo->files            = $draftid;

    // Completion defaults.
    $moduleinfo->completion       = COMPLETION_DISABLED;

    // ── 4. Create the module ──────────────────────────────────────────────────
    $cm = add_moduleinfo($moduleinfo, $course);

    if (empty($cm->coursemodule)) {
        throw new moodle_exception('error', 'local_aicoursegen', '',
            'add_moduleinfo() did not return a valid course-module object.');
    }

    return (int)$cm->coursemodule;
}